import { type Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import ToastProvider from '@/providers/ToastProvider'
import AuthLoadingWrapper from '@/components/auth/AuthLoadingWrapper'
import './globals.css'

/*
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});*/


export const metadata: Metadata = {
  title: "NutriFit - Seu Acompanhamento de Dieta Personalizado",
  description: "Acompanhamento personalizado de dietas, treinamentos e receitas para uma vida mais saudável",
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
/*
export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          <ToastProvider>
            <AuthLoadingWrapper>
              {children}
            </AuthLoadingWrapper>
          </ToastProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}